# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Policy_Consumer_Azure_Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_PROJECT_PATH: "src/Services/Consumer/Consumer.API"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Build with dotnet
        run: dotnet build ${{env.DOTNET_PROJECT_PATH}}/Consumer.API.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{env.DOTNET_PROJECT_PATH}} -c Release -o build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app-Consumer
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app-Consumer

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "policyconsumer"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8D4203C6B65C4EE9891C589518E6201C }}
          package: .
